name: Sync fork with upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # di√°rio, 03:00 UTC

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Configurar upstream
        run: |
          git remote add upstream https://github.com/Welves-de-Paula/calc-material.git
          git fetch upstream

      - name: Sincronizar branch main com calc-dev
        run: |
          git checkout main
          git merge upstream/calc-dev --no-edit

      - name: Push para o fork
        run: |
          git push origin main
